GET http://localhost:5000/api/users HTTP/1.1
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoicXVvY2JhbzAxIiwiaWF0IjoxNjU4NDc4NTY2LCJleHAiOjE2NTg0Nzg1OTZ9.7o4kNSZ49buxZ9r22NR5kLLiOXKCBjfq3xk_yAK8mXE
###

POST http://localhost:5000/api/signin HTTP/1.1
content-type: application/json

{
    "username": "quocbao01",
    "password": "145632"
}


POST http://localhost:5000/api/products HTTP/1.1
content-type: application/json

{
    "page": "0",
    "pageSize": "10"
}